@startuml EtudiantCarteAssociationSimple
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}

Etudiant "1" --- "1" CarteEtudiant

class Etudiant {
    - m_carteEtudiant : CarteEtudiant
}
class CarteEtudiant {
    - m_etudiant : Etudiant
}
@enduml