@startuml FactureDiagClasses
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor White
    BorderColor #000
}

Facture "1" --> "*" LigneFacture : contient
LigneFacture "1" --> "*" Article : référence

class Facture {
    - m_lignesFacture: List<LigneFacture>
    + NombreArticles : int <<get>>
    + TotalHorsTaxes : decimal <<get>>
    + TotalTaxesIncluses : decimal <<get>>
    + MontantTaxes : decimal <<get>>
    + AjouterArticle(article : Article, quantite : int)
    + RenvoyerChaine() : string
}
class LigneFacture {
    - m_quantite : int
    - m_article : Article
    + TotalHorsTaxes : decimal <<get>>
    + TotalTaxesIncluses : decimal <<get>>
    + MontantTaxes : decimal <<get>>
    + RenvoyerChaine() : string
}
class Article {
    - m_identifiant : string
    - m_nom : string
    - m_prixUnitaire : decimal
    - m_tauxTaxes : decimal
    + PrixUnitaire : decimal <<get>>
    + TauxTaxes : decimal <<get>>
    + RenvoyerChaine() : string
}
@enduml