@startuml AccessModifierPrivate
skinparam classAttributeIconSize 0
skinparam handwritten true
skinparam class {
    BackgroundColor White
    BorderColor #000
}

package Assembly1 #DDF {
    class Mere #BDD7EE {
        private MethodeAAcceder()
    }

    class FilleAssembly1 #EB935B {

    }

    Mere <|-- FilleAssembly1

    class AutreClasseAssembly1 #EB935B {

    }
}

package Assembly2 #DFF {
    class FilleAssembly2 #EB935B {

    }

    Mere <|-- FilleAssembly2

    class AutreClasseAssembly2 #EB935B {

    }
}

@enduml