@startuml InjectionDependances
skinparam classAttributeIconSize 0
skinparam handwritten true
skinparam class {
    BackgroundColor White
    BorderColor #000
}

DepotDonneesClients <|.. DepotDonneesClientsMariaDb
DepotDonneesClients <|.. DepotDonneesClientsXML
DepotDonneesClients <|.. DepotDonneesClientsFichierPlat


SousProgramme ..> DepotDonneesClients

class SousProgramme {
    [...]()
}

interface DepotDonneesClients {
    + ObtenirClient(p_identifiantClient : Guid) : Client {abstract}
    + ChercherClientsParNumeroTelephone(p_numeroTelephone : string) : List<Client> {abstract}
    + EnregistrerClient(p_client : Client) {abstract}
}

class DepotDonneesClientsMariaDb {
    + ctor(p_chaineConnexion : string)
    + ObtenirClient(p_identifiantClient : Guid) : Client <<override>>
    + ChercherClientsParNumeroTelephone(p_numeroTelephone : string) : List<Client> <<override>>
    + EnregistrerClient(p_client : Client) <<override>>
}

class DepotDonneesClientsXML {
    + ctor(p_nomFichierXML : string)
    + ObtenirClient(p_identifiantClient : Guid) : Client <<override>>
    + ChercherClientsParNumeroTelephone(p_numeroTelephone : string) : List<Client> <<override>>
    + EnregistrerClient(p_client : Client) <<override>>
}

class DepotDonneesClientsFichierPlat {
    + ctor(p_nomFichierFichierPlat : string)
    + ObtenirClient(p_identifiantClient : Guid) : Client <<override>>
    + ChercherClientsParNumeroTelephone(p_numeroTelephone : string) : List<Client> <<override>>
    + EnregistrerClient(p_client : Client) <<override>>
}

@enduml